scim2:
  resourcesPackage: com.codingronin.spring.webapp.scim.controller.v2
  baseUrl: http://localhost:9090/SimpleWebApp/api/scim/v2
  service-provider-config:
    documentationUri: http://www.simplecloud.info
    patch:
      supported: true
    bulk:
      supported: false
      maxOperations: 1000
      maxPayloadSize: 10000
    filter:
      supported: true
      maxResults: 25
    change-password:
      supported: true
    sort:
      supported: true
    etag:
      supported: true
    authenticationSchemes:
      - name: OAuth Bearer Token
        description: Authentication Scheme using OAuth Bearer Token Standard
        specUri: http://tools.ietf.org/html/draft-ietf-oauth-v2-bearer-01
        documentationUri: http://example.com/help/oauth.html
        type: oauthbearertoken
        primary: true